apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-broken-pipeline
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-broken-event-listener
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-broken-pipeline
rules:
  - apiGroups:
      - build.openshift.io
    resources:
      - buildconfigs
      - builds
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - build.openshift.io
    resources:
      - builds/log
    verbs:
      - get
  - apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-broken-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-broken-pipeline
subjects:
  - kind: ServiceAccount
    name: node-broken-pipeline
    namespace: REPLACE_WITH_PROJECT
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-broken-pipeline-run-creator
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - create
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-broken-event-listener-pipeline-run
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-broken-pipeline-run-creator
subjects:
  - kind: ServiceAccount
    name: node-broken-event-listener
    namespace: REPLACE_WITH_PROJECT
